version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nhcx_db
    volumes:
      - mysql_data:/var/lib/mysql

  consul:
    image: consul:1.10.3
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  vault:
    image: vault:1.9.2
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK

  platform-nhcx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platform-nhcx
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - kafka
      - consul
      - vault
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mysql_data:
